### ISSUE TITLE
Missing receiver metadata for project 26

### ISSUE THREAD

**Issue by tabanid** [MotusDev/ErrorLog#42]
The following batchIDs have no receiver metadata associated with them.

They are from receiverIDs:  488 503 and from 
2656 records with an NA receiverID.

BatchIDs from project 26 with missing receiver metadata

2451 2471 2473 2498 2500 2571 2576 2607 2609 2610 2612 2614 2616 2626 2627 2629 2630 2643 2658 2663 2693 2696 2702 2717 2718 2720 2721 2728 2731 2737 2740 2743 2746 2749 2754 2767 2768 2769 2770 2811 3391 3392 3396 3397 3399 3401 3403 3405 3407 3430 3433 3437 3439 3470 3472 3475 3478 3493 3504 3511 3519 3533 3538 3585 3586 3589 3590 3599 3603 3605 3614 3615 3616 3617 3618 3619 3621 3622 3628 3631 3634 3638 3644 3648 3651 3653 3654 3663 3666 3667 3817 3818 3835 3836
3837 3838 3839 3840 3841 3842 3844 3846 3847 3848 3851 3852 3853 3854 3855 3856 3857 3858 3862
3863 3864 3867 3868 3871 3873 3875 3876 3878 3880 3881 3882 3887 3891 3892 3893 3894 3895 3896
3898 3899 3900 3901 3903 3904 3905 3906 3907 3909 3910 3911 3912 3913 3914 3916 3917 3918 3919
3921 3922 3924 3925 3926 3927 3928 3929 3930 3931 3933 3934 3935 3936 3937 3938 3939 3940 3943
3945 3946 3947 3948 3949 3952 3958 3963 3966 3967 3970 3971 3972 3974 3975 3979 3980 3981 3984
3985 3986 3987 3988 3989 3992 3993 3994 3995 3996 3997 3998 4000 4001 4002 4004 4005 4006 4007
4008 4009 4010 4012 4013 4014 4015 4016 4018 4020 4021 4022 4023 4027 4028 4030 4032 4034 4037
4038 4039 4040 4041 4042 4043 4044 4045 4046 4047 4048 4049 4050 4051 4052 4053 4054 4055 4056
4057 4060 4061 4062 4064 4069 4070 4072 4073 4074 4075 4076 4077 4079 4081 4083 4084 4087 4089
4090 4091 4093 4094 4095 4097 4098 4099 4100 4102 4103 4105 4106 4107 4109 4110 4111 4112 4114
4115 4117 4118 4120 4123 4124 4125 4126 4127 4128 4131 4132 4138 4140 4142 4143 4144 4145 4148
4149 4150 4151 4608 4609

**Comment by zcrysler** [comment]
Potentially the same problem as https://github.com/MotusDev/ErrorLog/issues/34

**Comment by zcrysler** [comment]
project 38 is also missing metadata

No deviceID, recv etc., but sometimes there are GPS recordings, eg.:
batchID 628, runID 540466, hitID 10873049
batchID 647, runID 540497, hitID 10977206
batchID 102773, runID 20260586, hitID 277861375

There are also periods of missing receiver metadata that do at least contain deviceID and recv, but they should be associated with an existing deployment:
batchID 61, runID 19315, hitID 164258, detection on 2017-07-08 on Lotek-159 (deviceID 486), should be associated with recvDeployID 4093 which is active as of 2017-06-14 - but there is no associated receiver deployment metadata
batchID 125156, runID 23983506, hitID 385577879, detection on 2017-07-07 on Lotek-370 (deviceID 757), should be associated with recvDeployID 4231 which is active as of 2017-04-21

**Comment by cjardine-bsc** [comment]
Hi Guys, 

Yes, this is the same as issue number 34 (i.e. the metadata is actually missing and needs to be completed by the user, not an issue with pulling the data from the database). 

I thought we had solved this by using an outer join in the query, but looking at the database, it looks like Denis had to revert things while I was away. There is a note in the query saying that the deployID returned to R cannot be NULL. (there is probably an email about this buried somewhere in my post-vacation pile). 

If R can't manage the null deployID then the fix would be to change the query in the .motus file so that it uses the deviceID from the batch table instead of the recvDeps table. That way the alltags view would at least not be returning NULL for deviceID and be confusing users. Denis, sound good?

**Comment by zcrysler** [comment]
There are also periods with not metadata that do have existing deployments though:
batchID 61, runID 19315, hitID 164258, detection on 2017-07-08 on Lotek-159 (deviceID 486), should be associated with recvDeployID 4093 which is active as of 2017-06-14 - but there is no associated receiver deployment metadata
batchID 125156, runID 23983506, hitID 385577879, detection on 2017-07-07 on Lotek-370 (deviceID 757), should be associated with recvDeployID 4231 which is active as of 2017-04-21

**Comment by cjardine-bsc** [comment]
Hi Zoe, 

That issue is different than the one Phil was having. That error was happening because those deployments didn't have fixture_type populated. When Denis updated the query he accidentally reverted a left join to lk_fixture_type to an inner join, so those deployments were not being returned in the R package. 

I've fixed the query. A quick update to the metadata for project 38 should now resolve that issue.

**Comment by zcrysler** [comment]
Perfect - thanks for the clarification!
